'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import styles from './HeartSpinner.module.css';
const RED=[234,13,1] as const,WHITE=[255,255,255] as const;
type Plate={size:number,alpha:Uint8Array,red:Uint8Array,white:Uint8Array,depth:Float32Array};
type Point={x:number,y:number,z:number,nx:number,ny:number,nz:number,seed:number,white:boolean,side:boolean};
function hash(n:number){const v=Math.sin(n*91.733+17.17)*43758.5453;return v-Math.floor(v)}
function at(a:Uint8Array,s:number,x:number,y:number){x=Math.max(0,Math.min(s-1,x|0));y=Math.max(0,Math.min(s-1,y|0));return a[y*s+x]}
async function plate(src:string,size=520):Promise<Plate>{const im=new Image();im.src=src;await im.decode();const c=document.createElement('canvas');c.width=c.height=size;const g=c.getContext('2d',{willReadFrequently:true})!;g.imageSmoothingEnabled=false;g.drawImage(im,0,0,size,size);const p=g.getImageData(0,0,size,size).data,a=new Uint8Array(size*size),r=new Uint8Array(size*size),w=new Uint8Array(size*size),d=new Float32Array(size*size);for(let i=0;i<a.length;i++){a[i]=p[i*4+3]>100?1:0;r[i]=p[i*4]>120&&p[i*4]>p[i*4+1]*1.5?1:0;w[i]=p[i*4]>235&&p[i*4+1]>235&&p[i*4+2]>235?1:0}const dirs=[[1,0],[-1,0],[0,1],[0,-1],[1,1],[-1,1],[1,-1],[-1,-1]];for(let y=0;y<size;y++)for(let x=0;x<size;x++){const k=y*size+x;if(!a[k])continue;let md=90;for(const[dx,dy]of dirs){let q=1;for(;q<90;q++){const X=x+q*dx,Y=y+q*dy;if(X<0||Y<0||X>=size||Y>=size||!a[Y*size+X])break}md=Math.min(md,q*(dx!==0&&dy!==0 ? .707 : 1))}d[k]=Math.min(1,md/82)}return{size,alpha:a,red:r,white:w,depth:d}}
function makePoints(shape:Plate,light:Plate,fullness:number){const out:Point[]=[];let id=1,s=shape.size;for(let y=0;y<s;y++)for(let x=0;x<s;x++){const k=y*s+x;if(!shape.alpha[k]||(!light.red[k]&&!light.white[k]))continue;const X=(x/s-.5)*2.45,Y=(y/s-.5)*2.45,center=.975+.025*fullness*(1-Math.min(1,Math.abs(X)/1.1)),z=.43*center*Math.sin(shape.depth[k]*Math.PI/2),dx=(shape.depth[y*s+Math.min(s-1,x+2)]-shape.depth[y*s+Math.max(0,x-2)])*.11,dy=(shape.depth[Math.min(s-1,y+2)*s+x]-shape.depth[Math.max(0,y-2)*s+x])*.11;let nx=-dx,ny=-dy,nz=1,n=Math.hypot(nx,ny,nz);nx/=n;ny/=n;nz/=n;const seed=hash(id++),wh=!!light.white[k];out.push({x:X,y:Y,z,nx,ny,nz,seed,white:wh,side:false},{x:X,y:Y,z:-z,nx:-nx,ny:-ny,nz:-nz,seed:hash(id++),white:wh,side:false})}
  for(let y=1;y<s-1;y+=2)for(let x=1;x<s-1;x+=2){const k=y*s+x;if(!shape.alpha[k])continue;const edge=!at(shape.alpha,s,x+2,y)||!at(shape.alpha,s,x-2,y)||!at(shape.alpha,s,x,y+2)||!at(shape.alpha,s,x,y-2);if(!edge)continue;const X=(x/s-.5)*2.45,Y=(y/s-.5)*2.45,max=.42;for(let q=-7;q<=7;q++){const z=max*q/7;out.push({x:X,y:Y,z,nx:X>0?1:-1,ny:0,nz:0,seed:hash(id++),white:hash(id)<.08,side:true})}}
  return out}
function dot(b:Uint8ClampedArray,w:number,h:number,x:number,y:number,r:number,c:readonly number[]){for(let Y=y-r;Y<=y+r;Y++)for(let X=x-r;X<=x+r;X++){if(X<0||Y<0||X>=w||Y>=h||(X-x)*(X-x)+(Y-y)*(Y-y)>r*r+.2)continue;const i=(Y*w+X)*4;b[i]=c[0];b[i+1]=c[1];b[i+2]=c[2];b[i+3]=255}}
export default function HeartSpinner(){const canvas=useRef<HTMLCanvasElement>(null),raf=useRef(0),last=useRef(0),angleRef=useRef(0);const[playing,setPlaying]=useState(true),[angle,setAngle]=useState(0),[speed,setSpeed]=useState(10),[density,setDensity]=useState(92),[white,setWhite]=useState(82),[fullness,setFullness]=useState(45),[assets,setAssets]=useState<{shape:Plate,light:Plate,love:Plate,invite:Plate}|null>(null);
  useEffect(()=>{Promise.all([plate('/heart-study-03/love-lincoln.svg'),plate('/heart-study-03/reference-lighting.png'),plate('/heart-study-03/love-text.png'),plate('/heart-study-03/invitation-text.png')]).then(([shape,light,love,invite])=>setAssets({shape,light,love,invite}))},[]);const points=useMemo(()=>assets?makePoints(assets.shape,assets.light,fullness/100):[],[assets,fullness]);
  const render=useCallback((deg:number,exportSize?:number)=>{const c=canvas.current;if(!c||!assets)return;const w=Math.round(exportSize||Math.max(600,Math.min(1050,c.clientWidth*devicePixelRatio))),h=w;if(c.width!==w||c.height!==h){c.width=w;c.height=h}const g=c.getContext('2d')!,im=g.createImageData(w,h),b=im.data;for(let i=3;i<b.length;i+=4)b[i]=255;const t=deg*Math.PI/180,co=Math.cos(t),si=Math.sin(t),sc=w*.34,cx=w/2,cy=w*.5,view=points.map(p=>({p,X:p.x*co+p.z*si,Z:-p.x*si+p.z*co,nz:-p.nx*si+p.nz*co})).sort((a,z)=>a.Z-z.Z);
    for(const o of view){if(o.nz<-.08)continue;const p=o.p,turn=Math.abs(co),keep=p.side?.7+Math.abs(si)*.25:.76+turn*.24;if(p.seed>keep*density/100)continue;const color=p.white&&p.seed<white/100?WHITE:RED;dot(b,w,h,Math.round(cx+o.X*sc),Math.round(cy+p.y*sc),Math.max(1,Math.round(w/920)),color)}
    const face=co>.025?assets.love:co<-.025?assets.invite:null,sgn=co>.025?1:-1;if(face){const s=face.size,rad=Math.max(2,Math.ceil(w/850));for(let y=0;y<s;y++)for(let x=0;x<s;x++){if(!face.red[y*s+x])continue;let X=(x/s-.5)*2.45;if(sgn<0)X=-X;const Y=(y/s-.5)*2.45,z=.432*Math.sin(assets.shape.depth[y*s+x]*Math.PI/2)*sgn,sx=X*co+z*si,sz=-X*si+z*co;if(sz<-.04)continue;dot(b,w,h,Math.round(cx+sx*sc),Math.round(cy+Y*sc),rad,RED)}}g.putImageData(im,0,0)},[assets,density,points,white]);
  useEffect(()=>{render(angle)},[angle,render]);useEffect(()=>{if(!playing)return;const tick=(t:number)=>{if(last.current){angleRef.current=(angleRef.current+(t-last.current)*speed/1000)%360;setAngle(angleRef.current)}last.current=t;raf.current=requestAnimationFrame(tick)};raf.current=requestAnimationFrame(tick);return()=>{cancelAnimationFrame(raf.current);last.current=0}},[playing,speed]);const scrub=(v:number)=>{angleRef.current=v;setAngle(v)},save=()=>{render(angle,2400);requestAnimationFrame(()=>{const a=document.createElement('a');a.download=`lincoln-heart-${Math.round(angle)}deg.png`;a.href=canvas.current!.toDataURL('image/png');a.click();render(angle)})};
  return <main className={styles.page}><section className={styles.stage} aria-label="Rotating three-color stippled heart"><p className={styles.eyebrow}>Lincoln is for Lovers / Motion Study 03</p><canvas ref={canvas} className={styles.canvas}/><p className={styles.angle}>{angle.toFixed(1)}°</p></section><aside className={styles.panel}><h1>Heart<br/>Rotation</h1><p>Original stipple and lettering plates mapped onto a centered 3D turn.</p><div className={styles.buttons}><button className={`${styles.button} ${playing?styles.buttonActive:''}`} onClick={()=>setPlaying(v=>!v)}>{playing?'Pause':'Play'}</button><button className={styles.button} onClick={()=>scrub(0)}>Reset</button></div><div className={styles.group}><label className={styles.label}>Rotation <output>{Math.round(angle)}°</output></label><input className={styles.range} aria-label="Rotation angle" type="range" min="0" max="360" step="1" value={angle} onChange={e=>scrub(+e.target.value)}/><label className={styles.label}>Speed <output>{speed}°/s</output></label><input className={styles.range} aria-label="Rotation speed" type="range" min="3" max="24" value={speed} onChange={e=>setSpeed(+e.target.value)}/></div><div className={styles.group}><label className={styles.label}>Stipple density <output>{density}</output></label><input className={styles.range} aria-label="Stipple density" type="range" min="55" max="100" value={density} onChange={e=>setDensity(+e.target.value)}/><label className={styles.label}>White highlights <output>{white}</output></label><input className={styles.range} aria-label="White highlights" type="range" min="20" max="100" value={white} onChange={e=>setWhite(+e.target.value)}/><label className={styles.label}>Center fullness <output>{fullness}</output></label><input className={styles.range} aria-label="Center fullness" type="range" min="0" max="100" value={fullness} onChange={e=>setFullness(+e.target.value)}/></div><button className={styles.button} onClick={save}>Save 2400px still</button><div className={styles.swatches} aria-label="Exact palette"><i/><i/><i/></div><p className={styles.note}>#000000 / #EA0D01 / #FFFFFF<br/>Original decals. No text stippling.</p></aside></main>}
